apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-sample-app
  labels:
    app: java-sample-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-sample-app
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-java: "opentelemetry-operator-system/elastic-instrumentation"
      labels:
        app: java-sample-app
    spec:
      containers:
        - name: java-sample-app
          image: springio/gs-spring-boot-docker:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-sample-app
spec:
  selector:
    app: java-sample-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
